package main

// CVE-2022-30631 manual test

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"log"
)

func main() {
	var empty = []byte{0x1f, 0x8b, 0x08, 0x00, 0xa7, 0x8f, 0x43, 0x62, 0x00,
		0x03, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
	fmt.Println("I'm going to bytes.NewReader..", empty)
	repeted := bytes.Repeat(empty, 4e6)
	r := bytes.NewReader(repeted)
	fmt.Println("I'm going to gzip.NewReader..")
	z, err := gzip.NewReader(r)
	if err != nil {
		fmt.Println("NewReader error: ", err)
		log.Fatalf("NewReader: got %v, want nil", err)
	}
	// Prior to CVE-2022-30631 fix, this would cause an unrecoverable panic due
	// to stack exhaustion.
	fmt.Println("I'm going to Read..")
	_, err = z.Read(make([]byte, 10))
	if err != io.EOF {
		fmt.Println("Read error: ", err)
		err := fmt.Errorf("Reader.Read: got %v, want %v", err, io.EOF)
		fmt.Println(err.Error())
	}
}
